version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: plans42-db
    restart: always
    environment:
      POSTGRES_USER: plans42
      POSTGRES_PASSWORD: plans42pass
      POSTGRES_DB: plans42
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: